{
	"version": 1575522246,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/solo.png",
		"images/solo2.png",
		"images/cavaleiro-sheet0.png",
		"images/cavaleiro-sheet1.png",
		"images/plataform-sheet0.png",
		"images/jaula-sheet0.png",
		"images/explosão-sheet0.png",
		"images/tiledbackground.png",
		"images/tilemap.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/mato-sheet0.png",
		"images/mato-sheet1.png",
		"images/mato-sheet2.png",
		"images/mato2-sheet0.png",
		"images/mato2-sheet1.png",
		"images/mato2-sheet2.png",
		"images/valor-sheet0.png",
		"images/coletavel-sheet0.png",
		"images/particles.png",
		"images/garrafa-sheet0.png",
		"images/garrafa-sheet1.png",
		"images/garrafa2-sheet0.png",
		"images/garrafa2-sheet1.png",
		"images/coelho-sheet0.png",
		"images/coelho-sheet1.png",
		"images/mudadirecao-sheet0.png",
		"images/passaro-sheet0.png",
		"images/passaro-sheet1.png",
		"images/fim-sheet0.png",
		"images/papel-sheet0.png",
		"images/fogo-sheet0.png",
		"images/fogo-sheet1.png",
		"images/particlesagua.png",
		"images/porta-sheet0.png",
		"images/finalizafase-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/barreira-sheet0.png",
		"images/ok-sheet0.png",
		"images/terra_triste-sheet0.png",
		"media/coin_se.ogg",
		"media/trabalho_lindo.ogg",
		"media/fff.ogg",
		"media/street fighter ii-you win perfect (online-audio-converter.com).ogg",
		"media/gracas_a_deus.ogg",
		"media/gracas_a_deus2.ogg",
		"media/our-mountain_v003_looping (online-audio-converter.com).ogg",
		"media/kids cheering-soundbible.com-681813822.m4a",
		"media/kids cheering-soundbible.com-681813822.ogg",
		"media/water drop sound high-soundbible.com-1387792987.ogg",
		"media/breaking-metal.ogg",
		"media/water splash.ogg",
		"media/level_complete.ogg",
		"media/passos.ogg",
		"media/jump_03.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}